## LDA - Gibbs 采样
![](http://static.zybuluo.com/zhuanxu/i5x71enpnc3blencjahqi1rn/image_1c4gf6sh21qoa4cu1ke1aesr635o.png)

In [2]:
import numpy as np
import pymc3 as pm
#K, V, D = 2, 4, 3 # number of topics, words, documents
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_context("poster")
%matplotlib inline

In [3]:
K, V, D = 5, 10, 20 # number of topics, words, documents

#data = np.array([[1, 1, 1, 1], [1, 1, 1, 1], [0, 0, 0, 0]])

data_temp = np.random.randint(0,10,size=(D,V))

In [8]:
data_temp.shape # 20,10

(20, 10)

In [51]:
lda_model = pm.Model()
with lda_model:
    alpha = pm.HalfNormal('alpha', sd=1)
    eta = pm.HalfNormal('eta', sd=1)
    a1 = eta*np.ones(shape=(K,V))
    a2 = alpha*np.ones(shape=(D,K))
    theta = pm.Dirichlet('theta', a2, shape=(D,K)) # 每个文档的主题分布
    beta = pm.Dirichlet('beta', a1, shape=(K,V))  # 每个主题的词分布
    zs = [pm.Categorical("z_d{}".format(d), p=theta[d], shape=V) for d in range(D)] # 对于每篇文档，我们采样主题分布
    ws = [pm.Categorical("w_{}_{}".format(d,i), p=beta[zs[d][i]], observed=data_temp[d][i]) 
    for d in range(D) for i in range(V)]

In [52]:
zs  

[z_d0,
 z_d1,
 z_d2,
 z_d3,
 z_d4,
 z_d5,
 z_d6,
 z_d7,
 z_d8,
 z_d9,
 z_d10,
 z_d11,
 z_d12,
 z_d13,
 z_d14,
 z_d15,
 z_d16,
 z_d17,
 z_d18,
 z_d19]

In [53]:
# with lda_model:
#     ws = [pm.Categorical("w_{}_{}".format(d,i), p=beta[zs[d][i]], observed=data_temp[d][i]) 
#     for d in range(D) for i in range(V)]
#     z_d = [pm.Deterministic("z_d_{}_{}".format(d,i), z[d][i]) for d in range(D) for i in range(V)]

In [54]:
with lda_model:
    trace = pm.sample(2000)

Assigned NUTS to alpha_log__
Assigned NUTS to eta_log__
Assigned NUTS to theta_stickbreaking__
Assigned NUTS to beta_stickbreaking__
Assigned CategoricalGibbsMetropolis to z_d0
Assigned CategoricalGibbsMetropolis to z_d1
Assigned CategoricalGibbsMetropolis to z_d2
Assigned CategoricalGibbsMetropolis to z_d3
Assigned CategoricalGibbsMetropolis to z_d4
Assigned CategoricalGibbsMetropolis to z_d5
Assigned CategoricalGibbsMetropolis to z_d6
Assigned CategoricalGibbsMetropolis to z_d7
Assigned CategoricalGibbsMetropolis to z_d8
Assigned CategoricalGibbsMetropolis to z_d9
Assigned CategoricalGibbsMetropolis to z_d10
Assigned CategoricalGibbsMetropolis to z_d11
Assigned CategoricalGibbsMetropolis to z_d12
Assigned CategoricalGibbsMetropolis to z_d13
Assigned CategoricalGibbsMetropolis to z_d14
Assigned CategoricalGibbsMetropolis to z_d15
Assigned CategoricalGibbsMetropolis to z_d16
Assigned CategoricalGibbsMetropolis to z_d17
Assigned CategoricalGibbsMetropolis to z_d18
Assigned CategoricalGi

In [56]:
# 花了至少15分钟。。。真是太慢了。
for d in range(D):
    value_z=trace.get_values("z_d{}".format(d))
    print(value_z[1999])

[0 2 2 0 2 2 2 2 0 1]
[0 4 2 1 4 3 3 3 3 3]
[3 2 4 2 2 2 2 4 2 4]
[3 0 0 1 0 1 0 0 0 4]
[3 2 0 1 2 2 2 1 3 1]
[0 0 2 3 3 4 4 0 4 3]
[1 1 1 4 3 1 1 4 4 1]
[3 2 4 2 4 0 4 4 4 2]
[4 1 3 1 4 4 2 1 1 1]
[4 2 1 0 0 4 2 1 4 1]
[1 2 3 0 1 2 1 3 2 0]
[0 3 1 0 0 0 4 1 0 1]
[0 3 3 0 4 1 1 1 0 1]
[3 0 4 0 2 4 3 3 3 0]
[2 1 0 0 2 3 2 3 2 3]
[2 0 1 2 3 2 2 2 2 2]
[3 1 2 2 0 1 4 3 4 0]
[4 0 0 1 0 0 0 0 0 4]
[2 1 3 4 4 2 2 2 2 3]
[3 3 0 4 4 1 0 0 2 3]
